spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5430/polar_db
    username: user
    password: password
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
